### ISSUE TITLE
suggested updates on Prediction section in 03g

### ISSUE THREAD

**Issue by karticn-google** [statmike/vertex-ai-mlops#19]
1. First cell under **Retrieve Records for Prediction** Add `` to qualify the bigquery dataset in the query as shown below
**Before changes:**
`pred = bq.query(query = f"SELECT * FROM {BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE} WHERE splits='TEST' LIMIT {n}").to_dataframe()`
**After changes:**
```pred = bq.query(query = f"SELECT * FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}` WHERE splits='TEST' LIMIT {n}").to_dataframe()```

**Comment by karticn-google** [comment]
@statmike I have created this issue to update the query

**Comment by statmike** [comment]
I made the update and pushed it in a commit this morning.   Did this cause an error for you?  In

**Comment by statmike** [comment]
I see!  It depends on the projects name.  I added the backticks in my last push.
