### ISSUE TITLE
[04 - Vertex AI Custom Model - scikit-learn - in Notebook] Cannot deploy model to endpoint

### ISSUE THREAD

**Issue by tomchen29** [statmike/vertex-ai-mlops#23]
The notebook runs smoothly until "deploying the model to endpoint". Error screenshot is as below (via Google Photos):
https://photos.app.goo.gl/LgXedsdg89mqaXAz9
https://photos.app.goo.gl/dAto3r6mAat3jpGSA

Cloud Monitor has log as below:
https://photos.app.goo.gl/Qd4PW7uCXPZN1LxG7

How to Reproduce:
Run the notebook on Colab

**Comment by tomchen29** [comment]
Update: I was able to run the TensorFlow tutorial ("05 series") on Colab without issue, so I am highly skeptical there is a bug in sklearn image 'us-docker.pkg.dev/vertex-ai/training/scikit-learn-cpu.0-23:latest'.

**Comment by statmike** [comment]
@goodrules Hi Mike G, Would you be able to look at this question for deploying to endpoint?

**Comment by goodrules** [comment]
Sure thing, will take a look Monday first thing.

Have a great weekend,
Mike

**Comment by goodrules** [comment]
@tomchen29 thank you for identifying this as an issue. The code has been updated, a few minor tweaks and switching to using a pickle model vs joblib. Please let us know if you're still seeing an issue deploying.

**Comment by statmike** [comment]
going to close this issue for now but if there are any problem please continue to add comments here and we can reopen it

**Comment by statmike** [comment]
going to close this issue for now but if there are any problem please continue to add comments here and we can reopen it
