### ISSUE TITLE
On main branch, I see only notebooks 4a,4b,4c however in readme I do see a mention of 4g-4i. Where can I find that?

### ISSUE THREAD

**Issue by rsher60** [statmike/vertex-ai-mlops#34]
notebooks after 4c.

**Comment by statmike** [comment]
Hello @rsher60 , Thank you for trying out this series we are developing. @goodrules is currently working through the training job types to replicate what I did in the 05 - TensorFlow series.  I will let him update here on approximate timing for jobs d-i and in the short term in might be helpful to review the examples in the 05 series as they will very similar mechanically.

**Comment by goodrules** [comment]
@rsher60 the notebooks are actively being worked on, likely available in the next 1-2 weeks.  please refer to @statmike suggestion as they will be very similar to the 05 series.  thanks

**Comment by rsher60** [comment]
Thank you @statmike & @goodrules for all the awesome stuff. Looking forward to learn, improve and contribute in the future.
