### ISSUE TITLE
02c: failure of import aiplatform from google_cloud_pipeline_components

### ISSUE THREAD

**Issue by JonB451** [statmike/vertex-ai-mlops#51]
The following fails in current version:

`from google_cloud_pipeline_components import aiplatform as gcc_aip
`

**Comment by JonB451** [comment]
A workaround may be:

`from google.cloud import aiplatform as gcc_aip
`

**Comment by khadijakhaldi** [comment]
@JonB451 did you solve this ?

**Comment by statmike** [comment]
Hello @khadijakhaldi and @JonB451 
I just noticed this issue as closed.  I took a look and the SDK for `kfp` and `google_cloud_pipeline_components` have shift a little since this notebook was create.  I just pushed an update version of the notebook that should resolve this problem.  I tested it through running the pipeline and it worked.
Thank You!
@statmike

**Comment by JonB451** [comment]
Thanks @statmike . I've had to move onto something else for now, but will let you know when i get back to this. It's still high enough up my priorities that i hope that should be possible in the coming weeks so i will feedback if it worked here too. Thanks again, loads. You are a brilliant teacher, and generours, in material and in spirit it seems!

**Comment by JonB451** [comment]
@khadijakhaldi No, i didn't.

**Comment by JonB451** [comment]
@statmike Unfortunately, after pulling these changes, the imports do not work in my env. 

Despite replicating your procedures as closely as possible there was at least one difference, in the creation of the compute instance and its python version, if i remember correctly. I don't think 3.7 was available (due to a different region?) so i am on 3.9, as you can see below in the relevant bits i've cut out of the error.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

Cell In[4], line 8
_**----> 8 from google_cloud_pipeline_components.v1.automl.training_job import AutoMLTabularTrainingJobRunOp**_


File /opt/conda/lib/**python3.9**/site-packages/google_cloud_pipeline_components/v1/automl/training_job/__init__.py:16
_**---> 16 from google_cloud_pipeline_components.v1.automl.training_job.automl_forecasting_training_job.component import automl_forecasting_training_job as AutoMLForecastingTrainingJobRunOp**_


File /opt/conda/lib/python3.9/site-packages/google_cloud_pipeline_components/v1/automl/training_job/automl_forecasting_training_job/component.py:22
_**---> 22 from kfp.dsl import Input**_


ImportError: **cannot import name 'Input' from 'kfp.dsl' (/opt/conda/lib/python3.9/site-packages/kfp/dsl**/__init__.py)

**Comment by JonB451** [comment]
As the above error is while trying to import code about training jobs, the following seems relevant, except that i do not then know why it would work for you @statmike ...

[https://cloud.google.com/ai-platform/prediction/docs/runtime-version-list#2.6:~:text=Starting%20on%20October%206%2C%202022%2C%20you%20can%20no%20longer%20create%20training%20jobs%2C](https://cloud.google.com/ai-platform/prediction/docs/runtime-version-list#2.6:~:text=Starting%20on%20October%206%2C%202022%2C%20you%20can%20no%20longer%20create%20training%20jobs%2C)

2.6: Starting on October 6, 2022, you can no longer create training jobs,
2.3: Starting on December 9, 2021, you can no longer create training jobs,

**Comment by statmike** [comment]
Hello @JonB451 ,

Any notebook environment should work for this.   The main thing is the package installs with:

```
!pip install kfp google-cloud-pipeline-components google-cloud-aiplatform -q -U
```

To test this out I started a new environment, did these pip installs and tried importing and checking versions:

```
from google.cloud import aiplatform

import kfp
from kfp.v2 import compiler
#import kfp.v2.dsl as dsl
import google_cloud_pipeline_components as gcc_aip
from google_cloud_pipeline_components.v1.dataset import TabularDatasetCreateOp
from google_cloud_pipeline_components.v1.automl.training_job import AutoMLTabularTrainingJobRunOp
from google_cloud_pipeline_components.v1.endpoint import EndpointCreateOp, ModelDeployOp
```

- `!python --version` = 1.31.1
- `kfp.__version__` = 2.0.1
- `gcc_aip.__version__` = 2.3.0

Maybe try fresh pip installs with the -U option?

**Comment by JonB451** [comment]
Hello @statmike. 

Sorry i didn't respond sooner but i haven't been able to continue with this course before my GCP trial runs out. 

Although i cannot remember clearly now, i wanted to thank you for your reply and to respond. My memory is that you were right, and this was resolved as you suggested with fresh installs. 

All the best. Sad not to be continuing your great course!
