### ISSUE TITLE
Grounding Overview - RAG With BigQuery.ipynb:  ImportError: cannot import name 'documentai' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by stevewalker-de** [statmike/vertex-ai-mlops#65]
![image](https://github.com/user-attachments/assets/5a9489ad-57da-40fc-a294-979c2120e72c)

**Comment by statmike** [comment]
I think you are referring to [this notebook](../blob/main/Applied%20GenAI/Grounding%20Overview%20-%20RAG%20With%20BigQuery.ipynb) which has a section before the one in the screenshot titled "Installs (If Needed)" which will check for and install this package.  

Also, some new content around this topic is being built in this repository.  You might be interested in the [retrieval](../blob/main/Applied%20GenAI/Retrieval/readme.md) folder and in this case [this BigQuery workflow](../blob/main/Applied%20GenAI/Retrieval/Retrieval%20-%20BigQuery%20Vector%20Indexing%20And%20Search.ipynb) in that folder.
